name: culturebank
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=4.0.0=pyhd8ed1ab_0
  - arrow=1.2.3=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - backoff=2.2.1=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - blas=1.0=mkl
  - blessed=1.19.1=pyhe4f9e05_2
  - boltons=23.0.0=py311h06a4308_0
  - brotlipy=0.7.0=py311h5eee18b_1002
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cachecontrol=0.13.1=pyhd8ed1ab_0
  - cachecontrol-with-filecache=0.13.1=pyhd8ed1ab_0
  - cffi=1.15.1=py311h5eee18b_3
  - cleo=2.0.1=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - conda-content-trust=0.1.3=py311h06a4308_0
  - conda-package-handling=2.1.0=py311h06a4308_0
  - conda-package-streaming=0.8.0=py311h06a4308_0
  - crashtest=0.4.1=pyhd8ed1ab_0
  - croniter=1.4.1=pyhd8ed1ab_0
  - cryptography=39.0.1=py311h9ce1e76_2
  - dateutils=0.6.12=py_0
  - dbus=1.13.6=he372182_0
  - deepdiff=5.8.1=pyhd8ed1ab_0
  - distlib=0.3.7=pyhd8ed1ab_0
  - dulwich=0.21.3=py311h5eee18b_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - expat=2.2.10=h9c3ff4c_0
  - fastapi=0.99.1=pyhd8ed1ab_0
  - fmt=9.1.0=hdb19cb5_0
  - gh=2.36.0=ha8f183a_0
  - glib=2.69.1=he621ea3_2
  - h11=0.14.0=pyhd8ed1ab_0
  - icu=58.2=he6710b0_3
  - idna=3.4=py311h06a4308_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.0.1=pyhd8ed1ab_0
  - inquirer=3.1.3=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jaraco.classes=3.3.0=pyhd8ed1ab_0
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - keyring=24.2.0=py311h38be061_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libarchive=3.6.2=h6ac8c49_2
  - libcurl=8.1.1=h251f7ec_1
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmamba=1.4.1=h2dafd23_1
  - libmambapy=1.4.1=py311h2dafd23_1
  - libnghttp2=1.52.0=h2d74bed_1
  - libprotobuf=3.20.3=he621ea3_0
  - libsolv=0.7.22=he621ea3_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxml2=2.10.3=hcbfbd50_0
  - lightning-cloud=0.5.38=pyhd8ed1ab_0
  - lightning-utilities=0.9.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=h6a678d5_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46343
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - more-itertools=10.1.0=pyhd8ed1ab_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msgpack-python=1.0.3=py311hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - networkx=3.1=pyhd8ed1ab_0
  - ninja-base=1.10.2=hd09550d_5
  - numpy=1.25.2=py311h08b1b3b_0
  - numpy-base=1.25.2=py311hf175353_0
  - openssl=3.0.11=h7f8727e_2
  - ordered-set=4.1.0=pyhd8ed1ab_0
  - packaging=23.0=py311h06a4308_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.37=he7ceb23_1
  - pexpect=4.8.0=pyh1a96a4e_2
  - pip=23.1.2=py311h06a4308_0
  - pkginfo=1.9.6=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - pluggy=1.0.0=py311h06a4308_1
  - poetry=1.6.1=linux_pyha804496_0
  - poetry-core=1.7.0=pyhd8ed1ab_0
  - poetry-plugin-export=1.5.0=pyhd8ed1ab_0
  - psutil=5.9.0=py311h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycosat=0.6.4=py311h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.10.8=py311h5eee18b_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - pyopenssl=23.0.0=py311h06a4308_0
  - pyproject_hooks=1.0.0=pyhd8ed1ab_0
  - pyrsistent=0.18.0=py311h5eee18b_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.4=h955ad1f_0
  - python-build=0.10.0=pyhd8ed1ab_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-editor=1.0.4=py_0
  - python-installer=0.7.0=pyhd8ed1ab_0
  - python-multipart=0.0.6=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytorch-lightning=2.0.9=pyhd8ed1ab_0
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - rapidfuzz=2.13.7=py311ha02d727_0
  - readchar=4.0.5=pyhd8ed1ab_0
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h295c915_1
  - reproc-cpp=14.2.4=h295c915_1
  - requests-toolbelt=1.0.0=pyhd8ed1ab_0
  - rich=13.5.3=pyhd8ed1ab_0
  - ruamel.yaml=0.17.21=py311h5eee18b_0
  - secretstorage=3.3.3=py311h38be061_1
  - setuptools=67.8.0=py311h06a4308_0
  - shellingham=1.5.3=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.41.2=h5eee18b_0
  - starlette=0.27.0=pyhd8ed1ab_0
  - starsessions=1.3.0=pyhd8ed1ab_0
  - sympy=1.12=pyh04b8f61_3
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.12.1=pyha770c72_0
  - toolz=0.12.0=py311h06a4308_0
  - torchmetrics=1.1.2=pyhd8ed1ab_0
  - tqdm=4.65.0=py311h92b7b1e_0
  - traitlets=5.10.0=pyhd8ed1ab_0
  - trove-classifiers=2023.8.7=pyhd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - uvicorn=0.23.2=py311h38be061_0
  - virtualenv=20.24.4=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - websocket-client=1.6.3=pyhd8ed1ab_0
  - websockets=10.4=py311h5eee18b_1
  - wheel=0.38.4=py311h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.7.0=h295c915_1
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstandard=0.19.0=py311h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.0.0
      - accelerate==0.28.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - async-timeout==4.0.3
      - bitsandbytes==0.41.1
      - blis==0.7.11
      - cachetools==5.3.3
      - catalogue==2.0.10
      - certifi==2023.7.22
      - chardet==5.2.0
      - charset-normalizer==3.2.0
      - cloudpathlib==0.16.0
      - cmake==3.27.4.1
      - confection==0.1.3
      - cymem==2.0.8
      - dataproperty==1.0.1
      - datasets==2.14.5
      - dill==0.3.7
      - distro==1.9.0
      - docstring-parser==0.15
      - einops==0.6.1
      - en-core-web-lg==3.7.1
      - en-core-web-md==3.7.0
      - en-core-web-sm==3.7.0
      - evaluate==0.4.1
      - fairscale==0.4.13
      - filelock==3.12.3
      - fire==0.5.0
      - flash-attn==2.5.6
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - google-api-core==2.17.1
      - google-api-python-client==2.121.0
      - google-auth==2.28.2
      - google-auth-httplib2==0.2.0
      - googleapis-common-protos==1.63.0
      - greenlet==2.0.2
      - httpcore==1.0.4
      - httplib2==0.22.0
      - httpx==0.27.0
      - huggingface-hub==0.21.3
      - iniconfig==2.0.0
      - joblib==1.3.2
      - jsonargparse==4.24.1
      - jsonlines==4.0.0
      - langcodes==3.3.0
      - lightning==2.1.0rc0
      - lit==16.0.6
      - lm-eval==0.3.0
      - markupsafe==2.1.3
      - mbstrdecoder==1.1.3
      - multidict==6.0.4
      - multiprocess==0.70.15
      - murmurhash==1.0.10
      - ninja==1.11.1.1
      - nltk==3.8.1
      - numexpr==2.8.6
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.2.140
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - openai==1.13.3
      - pandas==2.1.0
      - pathvalidate==3.2.0
      - peft==0.5.0
      - phonenumbers==8.13.32
      - pillow==10.0.0
      - playwright==1.37.0
      - portalocker==2.8.2
      - preshed==3.0.9
      - presidio-analyzer==2.2.353
      - protobuf==4.25.3
      - pyarrow==13.0.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pybind11==2.11.1
      - pycountry==22.3.5
      - pyee==9.0.4
      - pyparsing==3.1.2
      - pytablewriter==1.0.0
      - pytest==7.4.0
      - pytest-base-url==2.0.0
      - pytest-playwright==0.4.2
      - python-slugify==8.0.1
      - pytorch-triton==2.1.0+6e4932cda8
      - pyyaml==6.0.1
      - regex==2023.8.8
      - requests==2.31.0
      - requests-file==2.0.0
      - responses==0.18.0
      - rouge-score==0.1.2
      - rsa==4.9
      - sacrebleu==1.5.0
      - safetensors==0.4.2
      - scikit-learn==1.3.0
      - scipy==1.11.2
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - smart-open==6.4.0
      - spacy==3.7.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlitedict==2.1.0
      - srsly==2.4.8
      - tabledata==1.3.3
      - tcolorpy==0.1.4
      - termcolor==2.3.0
      - text-unidecode==1.3
      - thinc==8.2.1
      - threadpoolctl==3.2.0
      - tiktokapi==6.1.1
      - tldextract==5.1.2
      - tokenizers==0.15.2
      - torch==2.1.0
      - torchvision==0.16.0
      - tqdm-multiprocess==0.0.11
      - transformers==4.38.2
      - triton==2.1.0
      - typepy==1.3.1
      - typer==0.9.0
      - typeshed-client==2.3.0
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - uritemplate==4.1.1
      - urllib3==2.0.4
      - wasabi==1.1.2
      - weasel==0.3.3
      - xxhash==3.3.0
      - yarl==1.9.2
